name: xiuminglib
channels:
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib=2.0.2
  - pillow
  - tqdm
  - trimesh
  - tensorflow
  - pip
  - pip:
    - opencv-python
  - sphinx=2.0.1
  - sphinx_rtd_theme
  - ipython
